spring:
  mail:
    host: smtp.qq.com
    username: 878636660@qq.com
    password: xxx  #授权码
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
